### ISSUE TITLE
May be let this property can be optimizaed

### ISSUE THREAD

**Issue by fengshaw1** [fengshaw1/vue3-ts-admin#1]
![image](https://user-images.githubusercontent.com/57137032/149089301-192bf461-8d9e-4ea2-946b-3a31a8d95f2f.png)
可以将该属性抽取出来、提前进行处理

**Comment by RishiKumarRay** [comment]
Can you help guide me , how to solve this?

**Comment by fengshaw1** [comment]
> Can you help guide me , how to solve this?

I have not think about a better way to solve this、may be tomorrow i can solve it!
